version: "2"
services:
  disqloverly:
    image: konopkov/disqloverly
    container_name: disqloverly
    ports:
      - "4000:4000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  books-service:
    build:
      context: ./books-service
    container_name: books-service

  # users-service:
  #   build:
  #     context: ./users-service
  #   container_name: users-service
